name: Daily Contribution

on:
  schedule:
    - cron: '0 12 * * *'  # Run daily at 12 PM UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  contribute:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Make daily contribution
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: python scripts/daily_contributor.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Daily contribution: $(date '+%Y-%m-%d')" || exit 0
        git push
