name: Issue Solver

on:
  schedule:
    - cron: '30 14 * * *'  # Run daily at 2:30 PM UTC
  issues:
    types: [opened, labeled]
  workflow_dispatch:

jobs:
  solve-issues:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Analyze and solve issues
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: python scripts/issue_solver.py
